export const CUSTOMER_TYPE = 'CUSTOMER_TYPE'; //客户类型
export const CONPAN_YTYPE = 'CONPAN_YTYPE'; // 企业类型
export const BRIDGE_TYPE = 'BRIDGE_TYPE'; //桥型
export const INFORMATION_CHANNEL = 'INFORMATION_CHANNEL';//信息来源渠道
export const PROJECT_PLAN_STATUS = 'PROJECT_PLAN_STATUS';//项目计划状态
export const CHANGE_TYPE = 'CHANGE_TYPE';//项目状态
export const BUSINESS_TYPE = 'BUSINESS_TYPE'; //提报类型
export const APPROVE_STATUS = 'APPROVE_STATUS';
export const Document_STATUS = 'Document_STATUS';//单据状态
export const STAGE = 'STAGE';//项目计划状态
export const THE_NATURE_OF_THE_PAYMENT = 'THE_NATURE_OF_THE_PAYMENT';//收款性质
export const EVALUATE = 'EVALUATE';//律所评价
